# Compose file para desenvolvimento em tempo real (Live Reload)
version: '3'

services:
  snipeit:
    build:
      context: .
      dockerfile: Dockerfile.alpine
    container_name: snipeit
    ports:
      - "8000:80"
    depends_on:
      redis:
        condition: service_started
      mysql:
        condition: service_healthy
    env_file:
      - .env.testing
    volumes:
      - .:/var/www/html
      - ./docker/startup_alpine.sh:/startup.sh
      - storage_dev:/var/lib/snipeit

  mysql:
    image: mysql:8.0
    container_name: snipeit-mysql
    volumes:
      - db_dev:/var/lib/mysql
    env_file:
      - .env.testing
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 2s
      retries: 5

  redis:
    image: redis:7.4.3
    container_name: snipeit-redis

  mailhog:
    image: mailhog/mailhog:v1.0.1
    container_name: snipeit-mailhog
    ports:
      - "8025:8025"

volumes:
  db_dev:
  storage_dev: